{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mirador.fullname" . }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        - path: /v1/traces
          pathType: Prefix
          backend:
            service:
              name: {{ include "mirador.fullname" $ }}
              port: { number: {{ index $.Values.service.ports "otlp-http" }} }
        - path: /v1/metrics
          pathType: Prefix
          backend:
            service:
              name: {{ include "mirador.fullname" $ }}
              port: { number: {{ index $.Values.service.ports "otlp-http" }} }
        - path: /v1/logs
          pathType: Prefix
          backend:
            service:
              name: {{ include "mirador.fullname" $ }}
              port: { number: {{ index $.Values.service.ports "otlp-http" }} }
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- toYaml .Values.ingress.tls | nindent 2 }}
  {{- end }}
{{- end }}
